SELECT TOP (1000) [studID]
      ,[studName]
      ,[studLastName]
      ,[studBirthdate]
      ,[studYearLevel]
      ,[studProgram]
      ,[createdByEmployee]
      ,[status]
  FROM [DB_Student_Partoza_IT13].[dbo].[tbStudent]
